---
- name: Install WeaveNet CNI
  hosts: all
  become: no
  tasks:

    - name: Apply WeaveNet CNI
      shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml