---
- name: Generate kubeconfig
  hosts: localhost
  tasks:
    - name: Create kubeconfig directory
      ansible.builtin.file:
        path: /path/to/kubeconfig/directory
        state: directory

    - name: Generate kubeconfig content
      ansible.builtin.template:
        src: kubeconfig_template.j2
        dest: /path/to/kubeconfig/directory/my_kubeconfig
      vars:
        cluster_name: my-cluster
        server_url: https://api.my-cluster.example.com
        ca_certificate: |
          -----BEGIN CERTIFICATE-----
          <base64-encoded-CA-certificate-data>
          -----END CERTIFICATE-----
        client_certificate: |
          -----BEGIN CERTIFICATE-----
          <base64-encoded-client-certificate-data>
          -----END CERTIFICATE-----
        client_key: |
          -----BEGIN RSA PRIVATE KEY-----
          <base64-encoded-client-key-data>
          -----END RSA PRIVATE KEY-----
