---
- name : Initilize the kubernetes worker server 
  hosts : nodes
  become: true
  tasks:
  - name: Install a list of packages for kubernetes
    yum:
      name:
        - iproute-tc
      state: present

  # Step 3.2: Join the nodes to the Kubernetes cluster using below code.
  - name: Copy the join command to server location
    copy: src=/tmp/join-command.sh dest=/tmp/join-command.sh mode=0777




  - name: Waits for the API server to come-up, don't start checking for 10 seconds
    ansible.builtin.wait_for:
      host: 172.16.10.100
      port: 6443
      delay: 10

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh
